name: GipMed
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  # common
  # - mkl < 2022  #for windows, better try to remove this line 
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pytest
  - pytest-xdist
  - python=3.8.12
  - scikit-learn
  - scipy
  - swig # needed to compile box2d
  - tqdm
  # pytorch
  - pytorch
  - pytorch-cuda=11.6
  - cudatoolkit
  - torchvision
  - torchtext
  # - cv2

  - pip
  - pip:
    - tensorboard

    